#multiplicacion con For de la tabla del 3

multiplicacion = ("vamos a multiplicar")
# declara la variable
multiplicacion = input ()

print ("3*1 =")
multiplicacion = input ()
print ("3*2 =")
multiplicacion = input ()
print ("3*3 =")
multiplicacion = input ()
print ("3*4 =")
multiplicacion = input ()
print ("3*5 =")
multiplicacion = input ()
print ("3*6 =")
multiplicacion = input ()
print ("3*7 =")
multiplicacion = input ()
print ("3*8 =")
multiplicacion = input ()
print ("3*9 =")
multiplicacion = input ()
print ("3*10 =")
multiplicacion = input ()