# Meses

mes = ("En que mes estamos")
# declara la variable
mes = input ()

print ("1. Enero")
mes = input ()
print ("2. Febrero")
mes = input ()
print ("3. Marzo")
mes = input ()
print ("4. Abril")
mes = input ()
print ("5. Maryo")
mes = input ()
print ("6. Junio")
mes = input ()
print ("7. Julio")
mes = input ()
print ("8. Agosto")
mes = input ()
print ("9. Septiembre")
mes = input ()
print ("10. Octubre")
mes = input ()
print ("11. Noviembre")
mes = input ()
print ("12. Dicciembre")
mes = input ()