# Meses

mes = ("En que mes estamos")
# declara la variable
mes = input ()

print ("Enero")
mes = input ()
print ("Febrero")
mes = input ()
print ("Marzo")
mes = input ()
print ("Abril")
mes = input ()
print ("Maryo")
mes = input ()
print ("Junio")
mes = input ()
print ("Julio")
mes = input ()
print ("Agosto")
mes = input ()
print ("Septiembre")
mes = input ()
print ("Octubre")
mes = input ()
print ("Noviembre")
mes = input ()
print ("Dicciembre")
mes = input ()